apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-keycloak-rw
spec:
  cluster:
    name: "pg-keycloak"
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
