apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-retain
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - nosharesock
 - actimeo=30
 - nobrl
reclaimPolicy: Retain
parameters:
  skuName: Standard_LRS
  accountAccessTier: Hot
  enableLargeFileShares: "true"
  shareNamePrefix: "tenant"
  shareAccessTier: "Hot"
  secretName: "azure-storage-account-secret"
