apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-premium-retain
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuname: Premium_LRS
  cachingMode: None
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
