apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argo-cd
      targetRevision: 7.7.16
      helm:
        valueFiles:
          - $values/argocd/argocd-helm-values.yaml
    - repoURL: 'https://github.com/tomlnd/gitops-demo.git'
      targetRevision: master
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
