apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: email@email.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          azureDNS:
            managedIdentity:
              clientID: xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
            subscriptionID: xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
            resourceGroupName: example-rg
            hostedZoneName: domain.com
            environment: AzurePublicCloud
